### ISSUE TITLE
Why does camb have the fortran compiler as a run requirement?

### ISSUE THREAD

**Issue by erykoff** [conda-forge/camb-feedstock#55]
### Comment:

Any conda forge installation of `camb` or something that depends on it gets a whole host of compilers because `{{ compiler('fortran') }}` is a run requirement.  I see that @beckermr touched this last.  Is this actually required?

**Comment by cmbant** [comment]
You don't need runtime fortran for most things, but you do for defining custom source functions
(https://camb.readthedocs.io/en/latest/ScalEqs.html box 28 etc)

**Comment by beckermr** [comment]
Yep that's correct. We added it so folks could use the custom runtime stuff.
